Repository SafeBoda/android-commons, pull requests merged in 2019-11, with the labels that each got.

#13 Updated library version in README.md
  README.md
Labels: bug

#15 App 303 : Firebase changes and track screen
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  app/src/main/java/com/safeboda/commons/analytics/AnalyticsService.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEventFactory.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/AmplitudeAnalyticsProvider.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/AnalyticsProvider.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/GoogleAnalyticsProvider.kt
  app/src/test/java/com/safeboda/commons/analytics/AnalyticsServiceUnitTest.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/TestAnalyticsEventFactory.kt
  dependencies.gradle
  projectFilesBackup/.idea/workspace.xml
Labels: enhancement

#17 Update README.md
  README.md
Labels: documentation

#18 Release v0.0.5
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  README.md
  app/src/main/java/com/safeboda/commons/analytics/AnalyticsService.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEventFactory.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsUser.kt
  app/src/main/java/com/safeboda/commons/analytics/extensions/MapExtensions.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/AmplitudeAnalyticsProvider.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/AnalyticsProvider.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/GoogleAnalyticsProvider.kt
  app/src/test/java/com/safeboda/commons/analytics/AnalyticsServiceUnitTest.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/TestAnalyticsEventFactory.kt
  build.gradle
  dependencies.gradle
  projectFilesBackup/.idea/workspace.xml
Labels: release

#19 App 309 : Fix Analytics Event bug
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsUser.kt
  app/src/main/java/com/safeboda/commons/analytics/extensions/MapExtensions.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/AmplitudeAnalyticsProvider.kt
  dependencies.gradle
Labels: bug

#20 App 317 : Make Event Factory a data class
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEventFactory.kt
  dependencies.gradle
Labels: bug

#21 Release v.0.0.7
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEventFactory.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsUser.kt
  app/src/main/java/com/safeboda/commons/analytics/extensions/MapExtensions.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/AmplitudeAnalyticsProvider.kt
  dependencies.gradle
Labels: release
