Repository SafeBoda/android-commons, pull requests merged in 2019-10, with the labels that each got.

#3 Mob 13 : Create the Amplitude analytics provider
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/safeboda/commons/analytics/provider/amplitude/AmplitudeAnalyticsProvider.kt
  dependencies.gradle
Labels: enhancement

#4 Mob 31 : Google Analytics Provider
  .idea/.name
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsProperty.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsUser.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/PropertyValues.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/amplitude/AmplitudeAnalyticsProvider.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/google/GoogleAnalyticsProvider.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/AnalyticsEventFactory.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/AnalyticsUserFactory.kt
  dependencies.gradle
Labels: enhancement

#7 Updated readme with new download link and updated upload
  README.md
Labels: documentation

#9 Mob 70 : Create release 0.0.2 of android-commons
  build.gradle
  dependencies.gradle
Labels: enhancement

#10 Release v0.0.2
  .gitignore
  .idea/.name
  .idea/inspectionProfiles/Project_Default.xml
  README.md
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/safeboda/commons/analytics/AnalyticsService.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsUser.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsValue.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/PropertyValues.kt
  app/src/main/java/com/safeboda/commons/analytics/extensions/MapExtensions.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/AmplitudeAnalyticsProvider.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/AnalyticsProvider.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/GoogleAnalyticsProvider.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/safeboda/commons/analytics/AnalyticsServiceUnitTest.kt
  app/src/test/java/com/safeboda/commons/analytics/entity/AnalyticsValueUnitTest.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/AnalyticsEventFactory.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/AnalyticsUserFactory.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/AnalyticsValueFactory.kt
  bintray.gradle
  build.gradle
  dependencies.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  install.gradle
  pull_request_template
  settings.gradle
Labels: release

#11 App 90 : Create AnalyticsEventFactory
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEventFactory.kt
  dependencies.gradle
Labels: enhancement

#12 Release v0.0.3
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEventFactory.kt
  dependencies.gradle
Labels: release
