Repository SafeBoda/android-commons, pull requests merged in 2020-01, with the labels that each got.

#24 App 567 : Update common docs
  README.md
Labels: bug, documentation

#25 App 555 : Limit the String of the event name to 40 char
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEventFactory.kt
Labels: enhancement

#23 App 560 : CleverTap client
  app/build.gradle
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/CleverTapAnalyticsProvider.kt
  dependencies.gradle
Labels: enhancement

#26 Release v0.0.8
  README.md
  app/build.gradle
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEvent.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsEventFactory.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/CleverTapAnalyticsProvider.kt
  dependencies.gradle
Labels: release

#27 App 602 : Update User values
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsUser.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/PropertyValues.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/CleverTapAnalyticsProvider.kt
  app/src/test/java/com/safeboda/commons/analytics/AnalyticsServiceUnitTest.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/AnalyticsUserFactory.kt
  dependencies.gradle
Labels: enhancement

#29 Release v0.0.9
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsUser.kt
  app/src/main/java/com/safeboda/commons/analytics/entity/PropertyValues.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/CleverTapAnalyticsProvider.kt
  app/src/test/java/com/safeboda/commons/analytics/AnalyticsServiceUnitTest.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/AnalyticsUserFactory.kt
  dependencies.gradle
Labels: release

#30 Release v0.0.10
  app/src/main/java/com/safeboda/commons/analytics/entity/AnalyticsUser.kt
  app/src/main/java/com/safeboda/commons/analytics/provider/CleverTapAnalyticsProvider.kt
  app/src/test/java/com/safeboda/commons/analytics/factory/AnalyticsUserFactory.kt
  dependencies.gradle
Labels: release

#31 App 631 : Update AnalyticsUser
  README.md
Labels: documentation
